name: Fetch Appstore Info

on:
  workflow_dispatch:
  schedule:
    - cron: "0/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: "14.x"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0.5"
      - run: gem install bundler:2.1.4
      - run: bundle update
      - run: npm install
      - run: node Sources/check_status.js
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          KEY_ID: ${{ secrets.KEY_ID }}
          ISSUER_ID: ${{ secrets.ISSUER_ID }}
          BUNDLE_ID: ${{ secrets.BUNDLE_ID }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          ABLY_CHANGE_LOG_GIST_ID: ${{ secrets.ABLY_CHANGE_LOG_GIST_ID }}
          ABLY_APP_UPDATE_CHANNEL_ID: ${{ secrets.ABLY_APP_UPDATE_CHANNEL_ID }}
          SLACK_WEB_CLIENT_API_KEY: ${{ secrets.SLACK_WEB_CLIENT_API_KEY }}
          CHANNEL_Q: ${{ secrets.CHANNEL_Q }}
          GROUP_ID_P: ${{ secrets.GROUP_ID_P }}
          LANGUAGE: "ko"
