name: Update README

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'  # 매달 1일 00:00에 실행

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Months
      run: python .github/scripts/update_readme.py
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Auto update months worked"
        git push
